
# Global environment
language: cpp
os: linux
dist: bionic

# Avoid double build because of the tagging in the build.
branches:
  except:
  - latest-passing-build

# Build stages and the conditionals for the stages
stages:
  - name: basic build & test
    if: "(NOT (TRAVIS_EVENT_TYPE = cron))"
  - name: extended build & test
    if: "(NOT (TRAVIS_EVENT_TYPE = cron))"
  - name: dist build
    if: "(NOT (TRAVIS_EVENT_TYPE = cron))"
  - name: deploy latest
    if: "(NOT type IN (pull_request)) AND (branch = master) AND (NOT (TRAVIS_EVENT_TYPE = cron))"

jobs:
  include:

# Basic builds

# Mac OSX
    - stage: basic build & test
      compiler: gcc
      os: osx
      env: BUILD=autotools
    - compiler: clang
      env: BUILD=autotools
      os: osx
      addons:
        apt:
          packages:
          - libc++-dev
# Linux
    - compiler: gcc
      env: BUILD=cmake CPP_STD=17
    - compiler: gcc
      env: BUILD=autotools
    - compiler: clang
      env: BUILD=autotools
      addons:
        apt:
          packages:
          - libc++-dev

# Extended builds, different C++ version and build tools
    - stage: extended build & test

# Mac OSX
      compiler: clang
      os: osx
      env: BUILD=cmake CPP_STD=17
      addons:
        apt:
          packages:
          - libc++-dev
    - compiler: gcc
      os: osx
      env: BUILD=cmake CPP_STD=14

# Linux
#   CMake different C++ versions with clang
    - compiler: clang
      env: BUILD=cmake CPP_STD=98
      addons:
        apt:
          packages:
          - libc++-dev
    - compiler: clang
      env: BUILD=cmake CPP_STD=11
      addons:
        apt:
          packages:
          - libc++-dev
    - compiler: clang
      env: BUILD=cmake CPP_STD=14
      addons:
        apt:
          packages:
          - libc++-dev
    - compiler: clang
      env: BUILD=cmake CPP_STD=17
      addons:
        apt:
          packages:
          - libc++-dev

#   CMake different C++ versions with gcc
    - compiler: gcc
      env: BUILD=cmake CPP_STD=98
    - compiler: gcc
      env: BUILD=cmake CPP_STD=11
    - compiler: gcc
      env: BUILD=cmake CPP_STD=14
    - compiler: gcc
      env: BUILD=cmake CPP_STD=17

#   New compilers can be added here. Need to be cleared when compiler becomes standard
    - compiler: gcc
      env: BUILD=cmake CPP_STD=17
        - CC=gcc-10
        - CXX=g++-10
      addons:
        apt:
          packages: ['g++-10']
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
    - compiler: clang
      env: BUILD=cmake CPP_STD=17
        - CC=clang-10
        - CXX=clang++-10
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages: ['clang-10', 'libc++-10-dev', 'libc++abi-10-dev']

#   Specific other tests
    - compiler: gcc
      env: BUILD=test_report
    - compiler: gcc
      env: BUILD=cmake_coverage
    - compiler: gcc
      env: BUILD=cmake_gtest
    - compiler: clang
      env: BUILD=autotools_gtest
    - compiler: gcc
      env: BUILD=autotools_cmake_install_test

#   MS DOS Build
    - env: BUILD=make_dos
      addons:
        apt:
          packages:
          - dosbox

#   Docker images. Need to be cleared at times
    - env: BUILD=docker_ubuntu_autotools
    - env: BUILD=docker_ubuntu_gcc10
    - env: BUILD=docker_ubuntu_dos

#   Create zip and tgz for distribution
    - stage: dist build
      env: BUILD=autotools_dist

#   Deploy to github releases
    - stage: deploy latest
      script:
      - git tag -f latest-passing-build -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
      - git push -f https://cpputest-travis:$GH_TOKEN@github.com/cpputest/cpputest.git --tags
      deploy:
        provider: releases
        token: $GH_TOKEN
        tag_name: latest-passing-build
        name: Latest passing build
        release_notes: This is the automatic release from Travis CI. Whenever a build passes, it gets released as Latest Passing Build.
        on:
          tags: false

before_script:
- export CPPUTEST_BUILD_DIR=$TRAVIS_BUILD_DIR/cpputest_build
- mkdir -p $CPPUTEST_BUILD_DIR && cd $CPPUTEST_BUILD_DIR

script:
- "../scripts/travis_ci_build.sh"

after_failure:
- "../scripts/travis_ci_after.sh"

after_success:
- "../scripts/travis_ci_after.sh"

notifications:
  slack:
    secure: oOx4AGIiJB+j1pkIxlLeQh5qp7TF89Sj+3RzJRQuo6z0HocTz9yJgXPlDh1H9rLj5SxK/UKsk+WFafVuPdWakQ40LeYO49C/+e+mCDcS0ujLka6dvIE8v0SEb1PuaAGjJWdhiviAhSqu9YOKPYZs37lD3oqepuEpxeiXwsur9QU=

env:
  global:
    secure: H6djbn5YP1P62n//ergaRZ4lIkneCzWp1Ok4F71kvvNiwlRzYDGll4kJT6MhVq6bBHeR81W/lwUd+RdjyqsJpVhj7DHXC/0k0h0xpAAm7LUhOl+6mIII1uhcMFqbeHvilwvDCzTQ6qv8Mzd1g0QfUECrmti9/U+/TTFJG0r0Zuc=
