language: cpp

dist: trusty
sudo: false

matrix:
    include:
    #- compiler: clang
      #env: BUILD=autotools
    - compiler: clang
      env: BUILD=cmake CPP11=OFF
    - compiler: clang
      env: BUILD=cmake CPP11=ON

    #- compiler: gcc
      #env: BUILD=autotools
    - compiler: gcc
      env: BUILD=cmake CPP11=OFF
    - compiler: gcc
      env: BUILD=cmake CPP11=ON


before_script:
    - export CPPUTEST_BUILD_DIR=$TRAVIS_BUILD_DIR/cpputest_build
    - mkdir -p $CPPUTEST_BUILD_DIR && cd $CPPUTEST_BUILD_DIR
script:
    - "../scripts/travis_ci_build.sh"
after_failure:
    - "../scripts/travis_ci_after.sh"
after_success:
    - "../scripts/travis_ci_after.sh"
