language: cpp

dist: bionic

jobs:
    include:
    - stage: "build & test"
      compiler: clang
      env: BUILD=cmake CPP_STD=98
      addons:
        apt:
          packages:
            - libc++-dev
    - compiler: clang
      env: BUILD=cmake CPP_STD=11
      addons:
        apt:
          packages:
            - libc++-dev
    - compiler: clang
      env: BUILD=cmake CPP_STD=14
      addons:
        apt:
          packages:
            - libc++-dev
    - compiler: clang
      env: BUILD=cmake CPP_STD=17
      addons:
        apt:
          packages:
            - libc++-dev

    - compiler: gcc
      env: BUILD=cmake CPP_STD=98
    - compiler: gcc
      env: BUILD=cmake CPP_STD=11
    - compiler: gcc
      env: BUILD=cmake CPP_STD=14
    - compiler: gcc
      env: BUILD=cmake CPP_STD=17

    - compiler: gcc
      env: BUILD=autotools
      addons:
        apt:
          packages:
            - valgrind
    - compiler: clang
      env: BUILD=autotools
      addons:
        apt:
          packages:
            - libc++-dev
            - valgrind

    - compiler: gcc
      env: BUILD=cmake_coverage
    - compiler: gcc
      env: BUILD=cmake_gtest
    - env: BUILD=make_dos
      addons:
        apt:
          packages:
            - dosbox
    - compiler: clang
      os: osx
      env: BUILD=cmake CPP_STD=17
      addons:
        apt:
          packages:
            - libc++-dev
    - compiler: gcc
      os: osx
      env: BUILD=cmake CPP_STD=14

    - compiler: gcc
      os: osx
      env: BUILD=autotools
      addons:
        apt:
          packages:
            - valgrind
    - compiler: clang
      env: BUILD=autotools
      os: osx
      addons:
        apt:
          packages:
            - libc++-dev
            - valgrind
    - env: BUILD=docker_ubuntu_autotools
    - env: BUILD=docker_ubuntu_gcc10
    - stage: "Final Build"
    - stage: "Deploy"
      script: ../scripts/travis_before_deploy.sh
      deploy:
        provider: releases
        # ⋮
        edge: true
        skip_cleanup: true
        on:
          tags: false

before_script:
    - export CPPUTEST_BUILD_DIR=$TRAVIS_BUILD_DIR/cpputest_build
    - mkdir -p $CPPUTEST_BUILD_DIR && cd $CPPUTEST_BUILD_DIR

script:
    - "../scripts/travis_ci_build.sh"

after_failure:
    - "../scripts/travis_ci_after.sh"

after_success:
    - "../scripts/travis_ci_after.sh"

before_deploy:


