
# Global environment
language: cpp
os: linux
dist: bionic

# Avoid double build because of the tagging in the build.
branches:
  except:
  - latest-passing-build

# Build stages and the conditionals for the stages
stages:
  - name: extensive daily tests
    if: type = cron
  - name: basic build & test
    if: type != cron
  - name: extended build & test
    if: type != cron
  - name: deploy latest
    if: "(NOT type IN (pull_request)) AND (branch = master) AND (type != cron)"

jobs:
  include:

# Basic builds

# Extended builds, different C++ version and build tools
    - stage: extended build & test

#   Specific other tests
    - compiler: gcc
      env: BUILD=autotools_cmake_install_test

#   Docker images. Need to be cleared at times
    - env: BUILD=docker_ubuntu_autotools
    - env: BUILD=docker_ubuntu_dos
    - env: BUILD=autotools_dist

    - arch: ppc64le
      compiler: gcc
      env: BUILD=autotools
    - arch: s390x
      compiler: gcc
      env: BUILD=autotools
    - arch: arm64
      compiler: gcc
      env: BUILD=autotools
    - compiler: clang
      env: BUILD=autotools_install_and_test_examples

#   Deploy to github releases
    - stage: deploy latest
      env: BUILD=autotools_dist
      script:
      - export DATE=`date`
      - git tag -f latest-passing-build -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER at $DATE"
      - git push -f https://cpputest-travis:$GH_TOKEN@github.com/cpputest/cpputest.git --tags
      - ../scripts/travis_ci_build.sh
      - pwd
      - ls
      deploy:
        provider: releases
        #:
        edge: true
        token: $GH_TOKEN
        tag_name: latest-passing-build
        name: Latest passing build
        release_notes: "This is the automatic release from Travis CI.\n\nWhenever a build passes, it gets released as Latest Passing Build.\n\nBuild number: $TRAVIS_BUILD_NUMBER\nDate: $DATE\nLog: $TRAVIS_BUILD_WEB_URL"
        file:
          - cpputest-latest.tar.gz
          - cpputest-latest.zip
        overwrite: true
        on:
          tags: false

before_script:
- export CPPUTEST_BUILD_DIR=$TRAVIS_BUILD_DIR/cpputest_build
- mkdir -p $CPPUTEST_BUILD_DIR && cd $CPPUTEST_BUILD_DIR

script:
- "../scripts/travis_ci_build.sh"

after_failure:
- "../scripts/travis_ci_after.sh"

after_success:
- "../scripts/travis_ci_after.sh"

notifications:
  slack:
    secure: oOx4AGIiJB+j1pkIxlLeQh5qp7TF89Sj+3RzJRQuo6z0HocTz9yJgXPlDh1H9rLj5SxK/UKsk+WFafVuPdWakQ40LeYO49C/+e+mCDcS0ujLka6dvIE8v0SEb1PuaAGjJWdhiviAhSqu9YOKPYZs37lD3oqepuEpxeiXwsur9QU=

env:
  global:
    secure: H6djbn5YP1P62n//ergaRZ4lIkneCzWp1Ok4F71kvvNiwlRzYDGll4kJT6MhVq6bBHeR81W/lwUd+RdjyqsJpVhj7DHXC/0k0h0xpAAm7LUhOl+6mIII1uhcMFqbeHvilwvDCzTQ6qv8Mzd1g0QfUECrmti9/U+/TTFJG0r0Zuc=
