version: 3.7.0-ci{build}

os:
- Windows Server 2012 R2

environment:
  matrix:
  - Platform: Cygwin32
  - Platform: MinGW32
    PlatformToolset: 4.8.5
  - Platform: MinGW64
    PlatformToolset: 4.8.5
  - Platform: MinGW32
    PlatformToolset: 5.3.0
  - Platform: MinGW64
    PlatformToolset: 5.3.0
  - Platform: Win32
    PlatformToolset: v90
  - Platform: Win32
    PlatformToolset: v100
  - Platform: Win32
    PlatformToolset: v140

install:
- ps: if ($env:PlatformToolset -like 'MinGW*') { choco install mingw --version $env:PlatformToolset $( if ($env:Platform -eq 'MinGW32') { Write-Output -forcex86 } ) | Out-Null }

build_script:
- ps: scripts\appveyor_ci_build.ps1

test_script:
- ps: scripts\appveyor_ci_test.ps1

artifacts:
- path: lib\CppUTest.lib
  name: CppUTest
