version: 3.7.0-ci{build}

os:
- Windows Server 2012 R2

environment:
  matrix:
  - PlatformToolset: MinGW
    Platform: Win32
  - PlatformToolset: MinGW
    Platform: x64
  - PlatformToolset: v90
  - PlatformToolset: v100

install:
- ps: if ($env:PlatformToolset -eq 'MinGW') { choco install mingw $( if ($env:Platform -eq 'Win32') { Write-Output -forcex86 } ) }

build_script:
- ps: scripts\appveyor_ci_build.ps1

test_script:
- ps: scripts\appveyor_ci_test.ps1

artifacts:
- path: lib\CppUTest.lib
  name: CppUTest

# Other configuration options
platform: Win32
configuration: Release
