version: 3.7.0-ci{build}

branches:
  only:
  - appveyor

os:
- Windows Server 2012 R2

environment:
  matrix:
  - PlatformToolset: v90
  - PlatformToolset: v100

build_script:
- ps: scripts\appveyor_ci_build.ps1

# Other configuration options
platform: Win32
configuration: Debug
