version: 2.1

jobs:
  latest-clang-autotools:
    docker:
      - image: silkeh/clang:latest
    environment:
      BUILD: autotools
      CXX: clang
    steps:
      - checkout
      - run: ./scripts/travis_ci_build.sh

workflows:
  basic-build-and-test:
    jobs:
      - latest-clang-autotools
