version: 2.1

jobs:
  latest-clang:
    docker:
      - image: silkeh/clang:latest
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  say-hello-workflow:
    jobs:
      - latest-clang
