---
name: Basic builds

on:
  push:
  pull_request:

jobs:
  mac-gcc-autotools:
    runs-on: macos-latest
    env:
      CC: gcc
      CXX: g++
    name: "Mac GCC Autotools"
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          brew install automake
          autoreconf -i .
          ./configure
          make tdd

  mac-clang-autotools:
    runs-on: macos-latest
    env:
      CC: clang
      CXX: clang++
    name: "Mac Clang Autotools"
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          brew install automake
          autoreconf -i .
          ./configure
          make tdd

  cmake:
    strategy:
      matrix:
        include:
          # Windows
          - os: windows-latest
            cpp_version: 17
          # Linux
          #   CMake different C++ versions with clang
          - os: ubuntu-latest
            cpp_version: 11
            cxx: clang++
            cc: clang
          - os: ubuntu-latest
            cpp_version: 14
            cxx: clang++
            cc: clang
          - os: ubuntu-latest
            cpp_version: 17
            cxx: clang++
            cc: clang
          #   CMake different C++ versions with gcc
          - os: ubuntu-latest
            cpp_version: 11
            cxx: g++
            cc: gcc
          - os: ubuntu-latest
            cpp_version: 14
            cxx: g++
            cc: gcc
          - os: ubuntu-latest
            cpp_version: 17
            cxx: g++
            cc: gcc
          # Mac OSX
          - os: macos-latest
            cpp_version: 17
            cxx: clang++
            cc: clang
          - os: macos-latest
            cpp_version: 14
            cxx: g++
            cc: gcc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - if: ${{ matrix.cxx }}
        run: echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV
      - if: ${{ matrix.cc }}
        run: echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV
      - name: Configure
        run: cmake -B build -S . -DCMAKE_CXX_STANDARD=${{ matrix.cpp_version }}
        if: ${{ matrix.cpp_version }}
      - name: Build
        run: cmake --build build
      - name: Test
        run: ctest --test-dir build

  linux-gcc-autotools:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++
    name: "Linux GCC autotools"
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          autoreconf -i .
          ./configure
          make tdd

  linux-clang-autotools:
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
    name: "Linux Clang autotools"
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          autoreconf -i .
          ./configure
          make tdd
