---
name: Basic builds

on:
  push:
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - uses: DoozyX/clang-format-lint-action@v0.14
        with:
          clangFormatVersion: 14
          source: examples

  automake:
    strategy:
      matrix:
        include:
          # Mac OSX
          - os: macos-latest
            cc: gcc
            cxx: g++
          - os: macos-latest
            cc: clang
            cxx: clang++
          # Linux
          - os: ubuntu-latest
            cc: gcc
            cxx: g++
          - os: ubuntu-latest
            cc: clang
            cxx: clang++
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - run: brew install automake
        if: ${{ startswith(matrix.os, 'macos') }}
      - if: ${{ matrix.cxx }}
        run: echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV
      - if: ${{ matrix.cc }}
        run: echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV
      - name: Configure
        run: |
          autoreconf -i .
          ./configure
      - name: Build and test
        run: make tdd

  cmake:
    strategy:
      matrix:
        include:
          # Windows
          - os: windows-latest
            cpp_version: 17
            preset: defaults
          # Linux
          #   CMake different C++ versions with clang
          - os: ubuntu-latest
            cpp_version: 98
            preset: Clang
          - os: ubuntu-latest
            cpp_version: 11
            preset: Clang
          - os: ubuntu-latest
            cpp_version: 14
            preset: Clang
          - os: ubuntu-latest
            cpp_version: 17
            preset: Clang
          #   CMake different C++ versions with gcc
          - os: ubuntu-latest
            cpp_version: 98
            preset: GNU
          - os: ubuntu-latest
            cpp_version: 11
            preset: GNU
          - os: ubuntu-latest
            cpp_version: 14
            preset: GNU
          - os: ubuntu-latest
            cpp_version: 17
            preset: GNU
          # Mac OSX
          - os: macos-latest
            cpp_version: 98
            preset: defaults
          - os: macos-latest
            cpp_version: 17
            preset: Clang
          - os: macos-latest
            cpp_version: 14
            preset: GNU
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Configure
        run: >
          cmake
          --preset ${{ matrix.preset }}
          -D CMAKE_CXX_STANDARD=${{ matrix.cpp_version }}
      - name: Build
        run: cmake --build cpputest_build --verbose
      - name: Test
        run: ctest --test-dir cpputest_build

  visualstudio-clangcl:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Configure
        run: >
          cmake
          -B build
          -G "Visual Studio 17 2022"
          -T ClangCL
      - name: Build
        run: cmake --build build --verbose
      - name: Test
        run: ctest --test-dir build
