---
name: Basic builds

on:
  push:
  pull_request:

jobs:
  mac-gcc-autotools:
    runs-on: macos-latest
    env:
      CC: gcc
      CXX: g++
    name: "Mac GCC Autotools"
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          brew install automake
          autoreconf -i .
          ./configure
          make tdd

  mac-clang-autotools:
    runs-on: macos-latest
    env:
      CC: clang
      CXX: clang++
    name: "Mac Clang Autotools"
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          brew install automake
          autoreconf -i .
          ./configure
          make tdd

  windows:
    runs-on: windows-latest
    env:
      CPP_STD: 17
    name: "Windows msbuild"
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          cmake -B build -S .
          cmake --build build
          ctest --test-dir build
