---
name: Basic builds

on:
  push:
  pull_request:

jobs:
  mac-gcc-autotools:
    runs-on: macos-latest
    env:
      CC: gcc
      CXX: g++
    name: "Mac GCC Autotools"
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          brew install automake
          autoreconf -i .
          ./configure
          make tdd

  mac-clang-autotools:
    runs-on: macos-latest
    env:
      CC: clang
      CXX: clang++
    name: "Mac Clang Autotools"
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          brew install automake
          autoreconf -i .
          ./configure
          make tdd

  mac-cmake:
    runs-on: macos-latest
    name: "Mac CMake"
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          cmake -B build -S . -DCMAKE_CXX_STANDARD=17
          cmake --build build
          ctest --test-dir build

  windows:
    runs-on: windows-latest
    name: "Windows msbuild"
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          cmake -B build -S . -DCMAKE_CXX_STANDARD=17
          cmake --build build
          ctest --test-dir build

  linux-gcc-cmake:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++
    name: "Linux GCC CMake"
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          cmake -B build -S . -DCMAKE_CXX_STANDARD=17
          cmake --build build
          ctest --test-dir build

  linux-gcc-autotools:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++
    name: "Linux GCC autotools"
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          autoreconf -i .
          ./configure
          make tdd

  linux-clang-autotools:
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
    name: "Linux Clang autotools"
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          autoreconf -i .
          ./configure
          make tdd
