---
name: Deploy Latest

"on":
  workflow_run:
    workflows: ["Basic builds"]
    branches: ["master"]
    types: ["completed"]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # https://github.com/actions/download-artifact/issues/3
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: basic.yml
          name: Distribution
          workflow_conclusion: success
          branch: master
      - name: Tag
        uses: anothrNick/github-tag-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: latest-passing-build
