name: Extended builds

on:
  push:
  pull_request:

jobs:
  test_report:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++
    steps:
      - name: Install tools
        run: sudo apt-get install -y ant-optional
      - name: Checkout
        uses: actions/checkout@main
      - run: |
          autoreconf -i .
          ./configure
          make check
          ./CppUTestTests -ojunit
          ./CppUTestExtTests -ojunit
          cp ./scripts/generate_junit_report_ant.xml .
          ant -f generate_junit_report_ant.xml
