name: Extended builds

on:
  push:
  pull_request:

jobs:
  test_report:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: sudo apt-get install -y ant-optional
      - name: Checkout
        uses: actions/checkout@main
      - run: |
          autoreconf -i .
          ./configure
          make check
          ./CppUTestTests -ojunit
          ./CppUTestExtTests -ojunit
          cp ./scripts/generate_junit_report_ant.xml .
          ant -f generate_junit_report_ant.xml

  make_dos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install tools
        run: |
          sudo apt-get install -y dosbox
          git clone https://github.com/cpputest/watcom-compiler.git watcom
          echo "WATCOM=$GITHUB_WORKSPACE/watcom" >> $GITHUB_ENV
          echo "CC=wcl" >> $GITHUB_ENV
          echo "CXX=wcl" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/watcom/binl" >> $GITHUB_PATH
          echo "CPPUTEST_HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Build
        run: |
          $CC --version
          make -f $CPPUTEST_HOME/platforms/Dos/Makefile clean
          make -f $CPPUTEST_HOME/platforms/Dos/Makefile
      - name: Test
        env:
          TERM: linux
        run: $CPPUTEST_HOME/platforms/Dos/alltests.sh

  cmake_install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install
        run: |
          cmake --preset GNU
          cmake --build cpputest_build/ -j
          ctest --test-dir cpputest_build/
          sudo cmake --install cpputest_build/
      - name: Use
        run: |
          cmake -B build -S examples
          cmake --build build -j
          ctest --test-dir build

  automake-no-long-long:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Configure
        run: |
          autoreconf -i .
          ./configure --disable-longlong
      - name: Build and test
        run: make tdd
