name: Extended builds

on:
  push:
  pull_request:

jobs:
  test_report:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: sudo apt-get install -y ant-optional
      - name: Checkout
        uses: actions/checkout@main
      - run: |
          autoreconf -i .
          ./configure
          make check
          ./CppUTestTests -ojunit
          ./CppUTestExtTests -ojunit
          cp ./scripts/generate_junit_report_ant.xml .
          ant -f generate_junit_report_ant.xml

  cmake_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: |
          pip install --user gcovr
          sudo apt install lcov
      - name: Checkout
        uses: actions/checkout@main
      - name: Configure
        run: >
          cmake
          -S .
          -B cpputest_build
          -D CMAKE_BUILD_TYPE=Debug
          -D C++11=ON
          -D COVERAGE=ON
          -D LONGLONG=ON
      - name: Build
        run: cmake --build cpputest_build
      - name: Test
        run: ctest --test-dir cpputest_build
      - name: Coverage
        run: lcov --capture --directory . --output-file lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
